/// Flutter icons Building
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Building
///      fonts:
///       - asset: fonts/Building.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Building {
  Building._();

  static const _kFontFam = 'Building';
  static const String? _kFontPkg = null;

  static const IconData building_town_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
